theme: jekyll-theme-slate
site_favicon: favicon.ico
title: FEniCS Project
description: Open-source finite element library
fenicsversion: 2019.1.0
fenicsxversion: 0.1.0
webroot: /web/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


