name: Build website

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y ruby-bundler
        name: Install prerequisites
      - uses: actions/checkout@v4
      - run: sudo bundle install
        name: Install bundle
      - run: pip3 install pillow pillow-heif
        name: Install Python dependencies for HEIC conversion
      - run: python3 _tools/update_galleries.py
        name: Update photo galleries
      - run: bundle exec jekyll build
        name: Build website

